### ISSUE TITLE
Using ss58_decode for validating an address

### ISSUE THREAD

**Issue by vnavascues** [polkascan/py-scale-codec#27]
Hi arjan!

I'm using `ss58_decode` for validating that an address (a str) has the right ss58 format. For instance
Not the right format:
```python
ss58_decode(
    address='14mB8stSf1vdP7WzbVr82YPgGGF7cBK9N7KxiVEac9UQgYj7',  // DOT address, ss58 1
    valid_ss58_format=2,
)
```
It has the right format:
```python
ss58_decode(
    address='GLVeryFRbg5hEKvQZcAnLvXZEXhiYaBjzSDwrXBXrfPF7wj',  // KSM address, ss58 2
    valid_ss58_format=2,
)
```

The recent changes [introduce a noop when the address starts with `0x`](https://github.com/polkascan/py-scale-codec/blob/master/scalecodec/utils/ss58.py#L46), which alters its functionality as a validation function (unless I remove `0x` from the address str). What is the reasoning behind? Should I use another way for validating addresses, e.g. Keypair?

Thanks!

**Comment by arjanz** [comment]
The reason for that check is that if the input for the `ss58_decode` function is already a public key, decoding is ignored. This behaviour is now [more in parity with the Polkadot-JS implementation](https://github.com/polkadot-js/common/blob/73708b72c719ea325ba3876528462e169eed2812/packages/util-crypto/src/address/decode.ts#L14), but on second thought I agree the behaviour is more ambiguous now and wouldn't mind removing it again if this makes it more clear.

I also understand the need for a more dedicated validation function, so what I can do is make a `is_valid_ss58_address` with an input for the ss58_format to be checked and which returns a mere `True` or `False`. I can also make this available for `substrate.is_valid_ss58_address` (`SubstrateInterface` already knows the `ss58_format`, also on the `Keypair` create functions I will add a check on the supplied `ss58_format` and otherwise raise a `ValueError`.

Will this work for you?

**Comment by vnavascues** [comment]
I think that keeping that noop for consistency with the Polkadot-JS but at the same time adding the `is_valid_ss58_address` would be great.
In fact this is my [is_valid_substrate_address](https://github.com/rotki/rotki/blob/d799ce5df6ad1fcac2a4ac1c7eb9275eff21ddee/rotkehlchen/chain/substrate/utils.py#L26) and [here](https://github.com/vnavascues/rotki/blob/d799ce5df6ad1fcac2a4ac1c7eb9275eff21ddee/rotkehlchen/tests/unit/test_substrate_utils.py#L25) some tests for kusama addresses.

Many thanks

**Comment by arjanz** [comment]
The `is_valid_ss58_address` you mentioned is also what I had in mind, I will add something like that in next release

**Comment by arjanz** [comment]
Released in https://github.com/polkascan/py-scale-codec/releases/tag/v0.10.59 and https://github.com/polkascan/py-substrate-interface/releases/tag/v0.11.17 as well

**Comment by vnavascues** [comment]
How quick! many thanks
