### ISSUE TITLE
Is it possible to distinguish between types with same name from diffrent pallets?

### ISSUE THREAD

**Issue by valentunn** [polkascan/py-scale-codec#35]
Hi. 
In our application, we're heavily relying on your JSON files with type definitions. It works really well, providing all the necessary information to construct dynamic types. However, recently we found, that there are two different types with the name `Phase` - the first one is from `System` pallete and corresponds to the block execution phase - [link](https://substrate.dev/rustdocs/v3.0.0/frame_system/enum.Phase.html). The seconds one is from `election-provider-multi-phase` pallete and corresponds to the election phase - [link](https://github.com/paritytech/substrate/blob/05445dc6d545095339c3977355f6d441b93685ba/frame/election-provider-multi-phase/src/lib.rs#L302). The problem is that in the default.json there is only one Phase type, which corresponds to the `System` one. While it is pretty easy to add a new type for  `election-provider-multi-phase` Phase into JSON file, it is not clear to me, how it is possible to distinguish between them while parsing metadata storage return type, for example. (it is Phase for both). In Polkadot js API, they are using additional [config file](https://github.com/polkadot-js/api/blob/a1f07e32743eed1c27bf06ca6fb9118afdbfa839/packages/types-known/src/modules.ts) for this purpose. Is it the only way or to do this?
Thanks for your help in advance

**Comment by arjanz** [comment]
At the moment this is not in the design, all types are global and not per pallet. But the scenario you are addressing is also on our todolist to address, because we also ran into issues before with ambiguous type name before, like `EquivocationProof` being used in different pallets. 

We are thinking of using a sort of dot-separated namespace like `Babe.EquivocationProof` and `Grandpa.EquivocationProof`, we are also using something like that for Ink-contracts types. We will keep you updated in this issue about when we will address this.

What you could try now if the generics differ, is to make separate entries for example:  `EquivocationProof<Header>` and `EquivocationProof<Hash>`, the resolver first tries to find the full entry, then tries to find `EquivocationProof`. (This is how we worked around this ambiguous type which resides in babe and grandpa).
