### ISSUE TITLE
Inconsistent parsing of Balances.Transfer events

### ISSUE THREAD

**Issue by stolpa4** [polkascan/py-scale-codec#57]
Hello, I've found that the simple code

```python
s = SubstrateInterface('wss://westend-rpc.polkadot.io', type_registry_preset='westend', ss58_format=42)
evts = s.get_events(block_hash=s.get_block_hash(x))

for evt in evts:
    event = evt.value
    if event['event_id'] == 'Transfer' and event['module_id'] == 'Balances':
        print(event['attributes'])
```

does produce different results for different block numbers. E.g. for the block with id 7862514 it produces
```
('5Ehed9osHF5LJ76SNVPh23FxZ6wqYyonDufVkWJBzvmf4eT2', '5FqbxNQkmrsVPPYfAgVDqFvMozyV9MmneJ1kZ3RkDK5ky842', 100000000000)
```

but for the block with id 7655084:

```
[{'type': 'AccountId', 'value': '5HpLdCTNBQDjFomqpG2XWadgB4zHTuqQqNHhUyYbett7k1RR'}, {'type': 'AccountId', 'value': '5HbwGTqpEw8LeUaCMtunWmCfFnJSN1gcnVjuqxAoDyuSc2rE'}, {'type': 'Balance', 'value': 1000000000000}]
```

So we have a tuple of values in the first case and list of dictionaries in the second. Is it deliberate?

**Comment by arjanz** [comment]
Yes this is because the parsing is more dictated from Substrate since MetadataV14 and before that it was more an interpretation and manual work from the library's side. Ideally we would make the parsing before MetadataV14 consistent, but this would be time-consuming and only adds value for only a few use-cases..
